artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: abisee/cnn_dailymail
  dataset_version: "3.0.0"
  local_data_dir: artifacts/data_ingestion/cnn_dailymail_data

data_validation:
  root_dir: artifacts/data_validation
  dataset_dir: artifacts/data_ingestion/cnn_dailymail_data
  STATUS_FILE: artifacts/data_validation/status.txt
  REQUIRED_FILES: ["train.csv", "validation.csv", "test.csv"]
  DATA_FORMATS: ["article", "highlights"]

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_dir: artifacts/data_ingestion/cnn_dailymail_data
  model_name: facebook/bart-base
  tokenizer_name: facebook/bart-base
  max_input_length: 1024
  max_target_length: 256

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_name: facebook/bart-base
  tokenizer_name: facebook/bart-base
  num_train_epochs: 3
  learning_rate: 5e-5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  weight_decay: 0.01
  save_total_limit: 2
  logging_steps: 100
  save_steps: 500
  warmup_steps: 500
  gradient_accumulation_steps: 8
  gradient_checkpointing: True

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation
  model_path: artifacts/model_trainer/final_model
  tokenizer_path: artifacts/model_trainer/final_model
  metric_file_name: evaluation_metrics.csv
